### ISSUE TITLE
Question: Can I run twoStageLCA on cells?

### ISSUE THREAD

**Issue by DongzeHE** [CHuanSite/SJD#1]
Hello,

Thanks for providing such an amazing tool.

I saw that in the [example analysis](https://chuansite.github.io/SJD/articles/StructralJointDecomposition.html), twoStageLCA is run on the given gene-by-cell count matrices, and the result has the same number of rows as the number of shared genes across those count matrices.

My question is that if I have a single-cell RNA-seq count matrix and a single-cell ATAC-seq peak count matrix, can I run twoStageLCA on cells to get a low-dimensional representation of each cell, instead of each gene? That it, instead of gene-by-cell count matrices, I transpose it to get cell-by-gene count matrices and use those cell-by-genes count matrices to run twoStageLCA()? 

Best,
Dongze

**Comment by CHuanSite** [comment]
Hi Dongze,

Thanks for reaching out!

Yes, you can just transpose the matrices and run the twoStageLCA package as it only requires the matrix dimension to match.

Huan

**Comment by DongzeHE** [comment]
Wonderful! Thank you so much!

**Comment by carlocolantuoni** [comment]
Dongze, we are implementing a number of analyses in similar ways to that which you described - did it work for you?
